### ISSUE TITLE
Additional checklist items

### ISSUE THREAD

**Issue by stronenv** [stronenv/turn-it-around#9]
I addition to our [Launch Checklists](https://wpspecialprojectsp2.wordpress.com/tae-handbook/launch-checklists/) we should make sure to test the following:

- [ ] 	Purchase a membership
- [ ] 	Assign a free membership
- [ ] 	While doing the above, also test that subscription/recurring payment is working as expected.
- [ ] 	Log in and access restricted content
- [ ] 	Navigate the site while not logged in
- [ ] 	Book a meeting
- [ ] 	Chat with the Chatbot
